### ISSUE TITLE
Webpack Entry Placement

### ISSUE THREAD

**Issue by jonmanzo** [TrackJs/js-integrations#3]
Does:

`window._trackJs = {
    token: "" // PUT YOUR TOKEN HERE
};`

need to be present prior to importing the trackjs package?

or could we simply add trackjs to the webpack entry config array, yet set the token within the bundled script?

**Comment by BrandesEric** [comment]
@jonmanzo the `window._trackJs` variable should be defined before the trackjs package is imported/executed.  How you accomplish that is entirely up to you :)  So in your case, if you'd prefer to use the entry array, you could do something like:

```js
{
    entry: ['trackJsConfig', 'trackjs']
}
```

Assuming the `trackJsConfig.js` file is executed first and sets up the `_trackJs` global var.  Maybe something like this?
```js
(function (){
  window._trackJs = { token: ""  }
})();
```

So basically the `trackjs` script is self-executing and will look for the global variable the minute it's run.  Simply importing the `trackjs` script causes execution and set up. As long as that global var is present on the page when it executes, everything will work :)

Does that help?  If you've got specific code snippets or issues just let me know!

**Comment by jonmanzo** [comment]
Excellent, that was my assumption.  No issues.  Appreciate the response!
